apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
        #making an app deployment to create the app container put make sure that db and memcache wotk first
    spec:
      containers:
      - name: vproapp
        image: esraaghazal/vprofileapp
        #every time container work pull the lateset image
        imagePullPolicy: Always
        ports:
        - name: vproapp-port
          containerPort: 8080
      initContainers:
        - name: init-mydb
          image: busybox
          args: ['-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
        - name: init-memcache
          image: busybox
          args: ['-c', 'until nslookup vprocache01.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
