apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
# using the default storageclass
  storageClassName: default
  # one pod can read and write at a time
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi